### ISSUE TITLE
Refactor - Grouped

### ISSUE THREAD

**Issue by csfar** [MyFormworks/Formworks#66]
List of Issues related to the initialization, JSON structure and components' view refactoring.
- [ ] Add FWForm class responsible for initialization using JSON and a style #67 
- [ ] Define and document the new JSON structure #68 
- [ ] Implement new JSON decoding process #69 
- [ ] Define and document new components' views #71 
- [ ] Implement new components' views #72 
- [ ] Document validators and their roles in a field's type #73 

**If there is an issue related to the refactoring missing from the list above, edit this issue and add a link to the missing issue.**

**Comment by csfar** [comment]
Deleted in favor of a project
